Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ParfumeOnlineShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ParfumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ParfumeOnlineShop.Interfaces;
using ParfumeOnlineShop.Models;
using ParfumeOnlineShop.ViewModel;

namespace ParfumeOnlineShop.Controllers
{
    public class ParfumeController : Controller
    {
        private readonly IParfumeRepository _parfumeRepository;
        private readonly ICategoryRepository _categoryRepository;

        public ParfumeController(IParfumeRepository parfumeRepository, ICategoryRepository categoryRepository)
        {
            _parfumeRepository = parfumeRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult List(string category)
        {
            //ViewBag.Category = "Women";            //1.put
            //return View(_parfumeRepository.Parfumes);

            //ParfumeListViewModel parfumeListViewModel = new ParfumeListViewModel();  //2.put
            //parfumeListViewModel.Parfumes = _parfumeRepository.Parfumes;
            //parfumeListViewModel.CurrentCategory = "Women parfumes";

            //return View(parfumeListViewModel);

            IEnumerable<Parfume> parfumes;

            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                parfumes = _parfumeRepository.Parfumes.OrderBy(p => p.ParfumeId);
                currentCategory = "All parfumes";
            }
            else
            {
                parfumes = _parfumeRepository.Parfumes.Where(p => p.Category.CategoryName == category)
                    .OrderBy(p => p.ParfumeId);
                currentCategory = _categoryRepository.Categories.FirstOrDefault(c => c.CategoryName == category).CategoryName;
            }
            return View(new ParfumeListViewModel
            {
                Parfumes = parfumes,
                CurrentCategory = currentCategory
            });
        }

        public IActionResult Details(int id)
        {
            var parfume = _parfumeRepository.GetParfumeById(id);

            if (parfume == null)
            {
                return NotFound();
            }
            return View(parfume);
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ParfumeOnlineShop.Interfaces;
using ParfumeOnlineShop.ViewModel;
using ParfumeOnlineShop.Models;

namespace ParfumeOnlineShop.Controllers
{
    public class ShoppingCartController : Controller
    {
    
        private readonly IParfumeRepository _parfumeRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IParfumeRepository parfumeRepository, ShoppingCart shoppingCart)
        {
            _parfumeRepository = parfumeRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            //test data
            /*test*/
            //ShoppingCartItem item = new ShoppingCartItem();
            //item.Parfume = _parfumeRepository.Parfumes.FirstOrDefault(p => p.ParfumeId == 1);
            //item.Amount = 2;
            //items.Add(item);
            /*end test*/
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int parfumeId)
        {
            var selectedParfume = _parfumeRepository.Parfumes.FirstOrDefault(p=>p.ParfumeId == parfumeId);

            if (selectedParfume !=null)
            {
                _shoppingCart.AddToCart(selectedParfume, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int parfumeId)
        {
            var selectedParfume = _parfumeRepository.Parfumes.FirstOrDefault(p => p.ParfumeId == parfumeId);

            if (selectedParfume !=null)
            {
                _shoppingCart.RemoveFromCart(selectedParfume);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/Carousel.cshtml
<div id="carouselExampleIndicators"  class="carousel slide offset-1" data-ride="carousel">
    <ol class="carousel-indicators">
        <li  data-target="#carouselExampleIndicators" data-slide-to="0" class="active bg-dark"></li>
        <li class="bg-dark" data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li class="bg-dark" data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li class="bg-dark" data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        <li class="bg-dark" data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img id="slika1" src="~/Images/Carousel/carousel1.jpg" alt="First slide" width="1000" height="500">
        </div>
        <div class="carousel-item">
            <img src="~/Images/Carousel/carousel2.jpg" alt="Second slide" width="1000" height="500">
        </div>
        <div class="carousel-item">
            <img src="~/Images/Carousel/carousel3.jpg" alt="Third slide" width="1000" height="500">
        </div>
        <div class="carousel-item">
            <img src="~/Images/Carousel/carousel4.jpg" alt="Third slide" width="1000" height="500">
        </div>
        <div class="carousel-item">
            <img src="~/Images/Carousel/carousel5.jpg" alt="Third slide"width="1000" height="500">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon bg-dark" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon bg-dark" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" class="navbar-right">
        <ul class="navbar-nav navbar-right">
            <li><a class="nav-link text-dark" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="navbar-nav navbar-right">
        <li><a class="nav-link text-dark" id="registerLink" asp-controller="Account" asp-action="Register">Register</a></li>
        <li><a class="nav-link text-dark" id="loginLink" asp-controller="Account" asp-action="Login">Log in</a></li>
    </ul>
}

Views/Shared/ParfumeOverViewSummary.cshtml
@model Parfume

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />
        <div class="caption">
            <h5 class="pull-right">@Model</h5>
            <h5>
                <a asp-controller="Parfume" asp-action="Details" asp-route-id="@Model.ParfumeId">@Model.Name</a>
            </h5>
            <p>@Model</p>
        </div>
        <div class="addToCart">
            <p class="button btn-sm">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                 asp-route-parfumeId="@Model.ParfumeId">Add to cart</a>
            </p>
        </div>
    </div>
</div>

Views/Shared/ParfumesOfTheMonthSummary.cshtml
@model Parfume

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />
        <div class="caption">
            <h5 class="pull-right">@Model.Price.ToString("c")</h5>
            <h5>
                <a asp-controller="Parfume"
                   asp-action="Details"
                   asp-route-id="@Model.ParfumeId">@Model.Name</a>
            </h5>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart">
            <p class="button btn-sm">
                <a class="btn btn-primary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-parfumeId="@Model.ParfumeId">Add to Cart</a>
            </p>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ParfumeOnlineShop</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />

    <link href="~/css/MyStyle.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white  border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ParfumeOnlineShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @await Html.PartialAsync("LoginPartial")
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact Us</a>
                        </li>
                        @await Component.InvokeAsync("CategoryMenu")
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ParfumeOnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>